## 26 FEB
### Assignment

### Q1

In [ ]:
Ans:- Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a 
Python list object, while array_list is a numpy ndarray object.

To print the data types of both variables, we can use the type() function as follows:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
So we can see that list_ has a data type of list, while array_list has a data type of numpy.ndarray

### Q2

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [ ]:
Ans:- To print the data type of each and every element of list_, we can use a for loop to iterate over the 
elements of the list and print the data type of each element using the type() function. Similarly, we can use the
dtype attribute of the numpy ndarray object to print the data type of each element of array_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(elem.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


In [ ]:
 that the elements in list_ are of type str, while the elements in array_list are of type <U1, which is a unicode
    string of length 1, because we initialized array_list with a list of strings.

### Q3

In [ ]:
Ans:- Yes, there will be a difference in the data type of the elements present in list_ and array_list.
By passing dtype=int when creating the numpy ndarray, we are forcing the elements in array_list to be of type int,
whereas in list_, the elements are still of type str.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for elem in list_:
    print(type(elem))

# Print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
that the elements in list_ are still of type str, whereas the elements in array_list are now of type int.

### Q4

In [ ]:
Ans:- the code to find the shape and size of num_array:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find shape of num_array
print("Shape of num_array:", num_array.shape)

# Find size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
We can see that the shape of num_array is (2, 3) and its size is 6.

### Q5

In [ ]:
Ans:- the code to create a numpy array of 3x3 matrix containing zeros only:

In [5]:
import numpy as np

# Create a numpy array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))

# Print the zeros_array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
We can see that the zeros_array contains 3 rows and 3 columns, and all its elements are zeros.

### Q6

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [ ]:
Ans:-  the code to create an identity matrix of shape (5,5) using numpy functions:

In [6]:
import numpy as np

# Create an identity matrix of shape (5,5)
identity_matrix = np.identity(5)

# Print the identity_matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
We can see that the identity_matrix contains 1 diagonally and other elements are 0, and it has a shape of (5,5).