Objective: The objective of this assignment is to gain practical experience with fundamental operations
in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on
tensors, and understanding the difference between TensorFlow constants and variables.
Part 1: Theoretical Questions
1. What are the different data structures used in Tensorflow?. Give some examples.
2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec
3. Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

Part 1: Theoretical Questions

1. Different data structures used in TensorFlow and examples:
TensorFlow uses two primary data structures for representing and manipulating data:
a. Tensors: Tensors are the fundamental data structures in TensorFlow. They are multi-dimensional arrays and can be of various shapes and data types. Tensors can represent scalars, vectors, matrices, and higher-dimensional arrays.
Examples:

- Scalar: tf.constant(5) # A scalar with value 5
- Vector: tf.constant([1, 2, 3]) # A 1D tensor (vector) with values [1, 2, 3]
- Matrix: tf.constant([[1, 2], [3, 4]]) # A 2D tensor (matrix) with values [[1, 2], [3, 4]]

b. Variables: Variables are special tensors that can hold trainable parameters in a TensorFlow model. Unlike constants, variables can be modified and updated during model training. They are typically used to represent model weights and biases.

In [ ]:
initial_value = tf.random.normal(shape=(3, 2))  # Creating a random initial value
weights = tf.Variable(initial_value)  # Creating a variable to hold model weights

2. Difference between TensorFlow constant and TensorFlow variable:

- TensorFlow Constant: A TensorFlow constant is an immutable tensor whose value cannot be changed once it is initialized. Constants are typically used to hold fixed data like input features or model hyperparameters. They are created using the tf.constant() function.

In [2]:
import tensorflow as tf

# Creating a TensorFlow constant
x = tf.constant([1, 2, 3])

- TensorFlow Variable: A TensorFlow variable is a mutable tensor whose value can be changed during model training. Variables are used to hold trainable parameters like model weights and biases. They are created using the tf.Variable() function.

In [3]:
import tensorflow as tf

# Creating a TensorFlow variable
initial_value = tf.random.normal(shape=(3, 2))  # Creating a random initial value
weights = tf.Variable(initial_value)  # Creating a variable to hold model weights

In summary, constants are used for fixed data, and their values cannot be changed. Variables, on the other hand, are used to hold trainable parameters and are updated during model training.

3. Process of matrix addition, multiplication, and element-wise operations in TensorFlow:

Matrix Addition:
To add two matrices in TensorFlow, you can use the tf.add() function or the + operator. The two matrices must have the same shape (number of rows and columns) for addition to be valid.

In [4]:
import tensorflow as tf

# Creating two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix addition
C = tf.add(A, B)
# Alternatively: C = A + B

print(C)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


Matrix Multiplication:
To multiply two matrices in TensorFlow, you can use the tf.matmul() function or the @ operator. The inner dimensions of the matrices must match for multiplication to be valid (i.e., the number of columns in the first matrix must be equal to the number of rows in the second matrix).

In [5]:
import tensorflow as tf

# Creating two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
C = tf.matmul(A, B)
# Alternatively: C = A @ B

print(C)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Element-wise Operations:
Element-wise operations are applied to corresponding elements of two tensors, and the two tensors must have the same shape. Common element-wise operations include addition, subtraction, multiplication, and division.

In [6]:
import tensorflow as tf

# Creating two tensors
A = tf.constant([1, 2, 3])
B = tf.constant([4, 5, 6])

# Element-wise addition
C = tf.add(A, B)
# Alternatively: C = A + B

# Element-wise multiplication
D = tf.multiply(A, B)
# Alternatively: D = A * B

print(C)  # Output: [5 7 9]
print(D)  # Output: [ 4 10 18]

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


Part2 : Practical Implementation
##### Talk 1: Creating and Manipulating Matrices
1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A.
2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B.
3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C.
4. Perform matrix addition between matrix A and matrix B, and store the result in matrix Dc
w. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [9]:
import tensorflow as tf

# Task 1: Create a normal matrix A with dimensions 2x2
A = tf.random.normal(shape=(2, 2))

# Task 2: Create a Gaussian matrix B with dimensions 2x2
B = tf.random.truncated_normal(shape=(2, 2))

# Task 3: Create a matrix C with dimensions 2x2, drawn from a normal distribution with mean 2 and std deviation 0.5
mean = 2.0
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Task 4: Perform matrix addition between A and B, store the result in matrix D
D = tf.add(A, B)

# Task 5: Perform matrix multiplication between C and D, store the result in matrix E
E = tf.matmul(C, D)

# Display the values of matrices A, B, C, D, and E
print("Matrix A:")
print(A.numpy())
print()

print("Matrix B:")
print(B.numpy())
print()

print("Matrix C:")
print(C.numpy())
print()

print("Matrix D (Result of A + B):")
print(D.numpy())
print()

print("Matrix E (Result of C * D):")
print(E.numpy())
print()

Matrix A:
[[ 0.00895057 -0.4438249 ]
 [-0.3456169   1.182607  ]]

Matrix B:
[[ 0.17338254 -0.25919348]
 [ 1.2427725  -1.0744277 ]]

Matrix C:
[[2.0372036 1.7443429]
 [2.984256  1.8879142]]

Matrix D (Result of A + B):
[[ 0.18233311 -0.70301837]
 [ 0.8971555   0.10817933]]

Matrix E (Result of C * D):
[[ 1.9363966 -1.2434896]
 [ 2.2378814 -1.8937534]]



This code will create and display the values of matrices A, B, C, D, and E as per the given tasks. The tf.random.normal function is used to generate random normal distributions, and tf.truncated_normal is used to create a Gaussian matrix with truncated values. The matrix addition and multiplication are performed using tf.add and tf.matmul functions, respectively.

Task2 : Peforming Additional Matrix Operations
Tc Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
function.
1.  Calculate the transpose of matrix F and store the result in matrix G.
2. Calculate the elementDwise exponential of matrix F and store the result in matrix H.
3. Create a matrix I by concatenating matrix F and matrix G horizontally.
4. Create a matrix J by concatenating matrix F and matrix H vertically.

In [10]:
import tensorflow as tf

# Task 1: Create a matrix F with dimensions 2x2, initialized with random values using random_uniform
F = tf.random.uniform(shape=(2, 2))

# Task 2: Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)

# Task 3: Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)

# Task 4: Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)

# Task 5: Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)

# Display the values of matrices F, G, H, I, and J
print("Matrix F:")
print(F.numpy())
print()

print("Matrix G (Transpose of F):")
print(G.numpy())
print()

print("Matrix H (Element-wise Exponential of F):")
print(H.numpy())
print()

print("Matrix I (Concatenation of F and G horizontally):")
print(I.numpy())
print()

print("Matrix J (Concatenation of F and H vertically):")
print(J.numpy())
print()

Matrix F:
[[0.7684164  0.34568357]
 [0.25993228 0.47682774]]

Matrix G (Transpose of F):
[[0.7684164  0.25993228]
 [0.34568357 0.47682774]]

Matrix H (Element-wise Exponential of F):
[[2.1563487 1.4129554]
 [1.2968422 1.610956 ]]

Matrix I (Concatenation of F and G horizontally):
[[0.7684164  0.34568357 0.7684164  0.25993228]
 [0.25993228 0.47682774 0.34568357 0.47682774]]

Matrix J (Concatenation of F and H vertically):
[[0.7684164  0.34568357]
 [0.25993228 0.47682774]
 [2.1563487  1.4129554 ]
 [1.2968422  1.610956  ]]



This code will create matrices F, G, H, I, and J based on the given tasks and display their values. The tf.transpose() function is used to calculate the transpose of matrix F, and the tf.exp() function is used to calculate the element-wise exponential of matrix F. The tf.concat() function is used to concatenate matrices F and G horizontally and matrices F and H vertically